### PR TITLE
Add Google analytics code in head tag

### LINKED ISSUE #29: Add analytics to the website
Let's discuss here, if we need to add analytics to the website.

### PR DESCRIPTION
**Pull request by inovizz**
Fixes #29.

### CODE REVIEW

**Review by ananyo2012 — APPROVED** [review]
LGTM. @inovizz Are you using your own Google analytics account for this ?

**Comment by inovizz** [comment]
> LGTM. @inovizz Are you using your own Google analytics account for this ?

No, I created one using hyderabadpyconf@gmail.com

**Comment by ananyo2012** [comment]
Ok got it. Merging this.

**Comment by ananyo2012** [comment]
@all-contributors add @inovizz for code, design, event organizing, ideas, project management

**Pull request merged**
