### PR TITLE
header bg changes, performance optimization changes

### LINKED ISSUE #31: Remove transparent header and make it constant as black
image

Reference above.

### PR DESCRIPTION
**Pull request by bhansa**
Fixes #31

### CODE REVIEW

**Comment by inovizz** [comment]
@bhansa - I should have advised this before but after looking at the preview I see that black colour seem to be little off. So I have a couple of points for solution  -

1. The theme of the website is based on the blue colour mostly, so we can try header with a dark blue colour, that may look a little better
2. if not 1st one, then we can think of changing the theme colour itself, make it black(the buttons, footer etc.) if it looks good?

I, @ananyo2012 and you and get on a call and discuss in detail if needed.

**Comment by ananyo2012** [comment]
This one looks good to me. But let's try the 1st option @inovizz suggested. @bhansa Let's do this in a separate PR so that we can compare previews.

**Comment by bhansa** [comment]
@ananyo2012  @inovizz  Right now the header bg color is `#141c25` which is close to dark blue. I guess which is fine now.
I'll try to come with a new theme for website to align things properly. I will address this in a separate PR.

**Comment by bhansa** [comment]
This PR contains changes related to accessibility and performance as well, so let's merge them.

**Comment by ananyo2012** [comment]
Agree. Let's go ahead and merge this and address the design modification issues in a different PR.

**Pull request merged**
