### PR TITLE
updated pyconf logo, removed buy tickets button from header mobile.

### LINKED ISSUE #20: Update new logo of PyConf Hyderabad 2019
@bhansa Creating this issue for the new logo. Please update when ready.

### PR DESCRIPTION
**Pull request by bhansa**
Updated logo.
Fixes #20

### CODE REVIEW

**Comment by ananyo2012** [comment]
@bhansa @subuhani Can we have a logo with smaller dimension for the website ?

Also we need a favicon with just the python logo with the theme. But that can be done in a separate issue.

**Comment by bhansa** [comment]
@ananyo2012 what about the size which I added to the preview, currently dimensions are 204x64.

**Comment by bhansa** [comment]
Merging this for now, will follow up for more updates.

**Comment by ananyo2012** [comment]
@bhansa Yeah it's still big. We need to shorten it more.

**Pull request merged**
