### PR TITLE
Sponsors

### PR DESCRIPTION
**Pull request by bhansa**
WIP, adding sponsors and sponsor modal.

### CODE REVIEW

**Comment by ananyo2012** [comment]
@bhansa Can we adjust the grids so that Community Partner, In-kind appears in same line ?

**Comment by ananyo2012** [comment]
@inovizz I was thinking if we should arrrange sponsors 3 in a row to utilize the space. The line up will be

Line 1: 2 Platinum + 1 Gold Sponsor

Line 2: 2 Silver + 1 Associate

Line 3: 1 In-kind + 1 Community Partner

What do you think ?

**Comment by inovizz** [comment]
@ananyo2012 - yes that sounds good.

**Comment by ananyo2012** [comment]
@bhansa You can go ahead with the above suggestion then.

**Pull request merged**
