### PR TITLE
adding event schema

### PR DESCRIPTION
**Pull request by bhansa**
#33

### CODE REVIEW

**Comment by ananyo2012** [comment]
@bhansa Let's add `keywords` and `about` attributes to enable better search results. Also have the top level navigation items in schema.

**Comment by bhansa** [comment]
I'll keep on updating this, as we add details.

**Comment by ananyo2012** [comment]
@bhansa Let's just add the ones I suggested and merge this in.

**Comment by ananyo2012** [comment]
Looks good @bhansa ! Let's merge this in. Also let's Observe the search result in the next one week and update the keywords for better SEO performance after that.

**Pull request merged**
