### PR TITLE
Enable Github Actions For Deployment

### PR DESCRIPTION
**Pull request by arunc009**

### CODE REVIEW

**Comment by arunc009** [comment]
@ananyo2012 Please Review.

**Comment by ananyo2012** [comment]
@arunchaudhary09 The execution of entrypoint.sh seems to be failing due to permission issues. I think you need to make that executable somewhere in the run script.

**Comment by arunc009** [comment]
It failed for the first time after pushing then i took a look at it and made the `entrypoint.sh` executable. 
```
arunc@arun:~/arunchaudhary09-github/hydpyconf2019$ git branch; ls -al | grep entrypoint.sh
  TASK-Enable_CI_CD
* ci-cd
  master
-rwxrwxr-x 1 arunc arunc    799 Nov 21 23:41 entrypoint.sh
```
It should be good now. @ananyo2012

**Comment by ananyo2012** [comment]
Is there any way to retrigger the deployment in the PR ?

**Comment by ananyo2012** [comment]
Also does git remember the file permissions? I am not totally sure about
that

**Comment by bhansa** [comment]
@arunchaudhary09 one check is seems to be failing, please check once.

**Comment by arunc009** [comment]
Took a look at it and this is the check which is failing: 
```
/usr/bin/docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/entrypoint.sh\": permission denied": unknown.
##[error]Docker run failed with exit code 126
```
And the above script has been made executable here at `https://github.com/HydPy/hydpyconf2019/commit/8185873e5b70a7d54666beb9279b2acb3e49fc28` Though, it says no changes content wise but if you could actually clone the repo and change the branch to `ci-cd`. You could see that the script is executable now. 

For now to trigger this action. We need to merge this PR and we will take a look at it once again if it fails in any case.

**Comment by arunc009** [comment]
@bhansa @ananyo2012

**Comment by ananyo2012** [comment]
Ok let's merge this and see what happens

**Pull request merged**
