### PR TITLE
added link for devsprints

### LINKED ISSUE #79: Add Devsprint link
Add a button linking to the Devsprint page - https://github.com/HydPy/hydpyconf2019/wiki/PyConf-Hyderabad-2019-Devsprint

### PR DESCRIPTION
**Pull request by bhansa**
Fixes #79

### CODE REVIEW

**Comment by ananyo2012** [comment]
@bhansa I actually want this as a hero button and also the first item in the More dropdown.

**Comment by bhansa** [comment]
Okay, where you want the hero button to be placed?
Something similar to get tickets and submit button?

**Comment by ananyo2012** [comment]
Yes just beside the Submit Talk button

**Comment by ananyo2012** [comment]
@bhansa Can you update this ? I will start reaching out mentors starting this weekend. So want this to be live soon.

**Comment by bhansa** [comment]
@ananyo2012 let me know how this looks.

**Comment by ananyo2012** [comment]
Looks good. Merge it in

**Pull request merged**
